name: Backend Staging Environment

on:
  push:
    branches:
      - staging
    paths:
      - 'application/backend/**'
      - '.github/workflows/backend-staging.yml'
      - '.github/workflows/backend-reusable.yml'
      - '!application/backend/**/*.md'
      - '!**/*.md'
      - '!application/backend/**/*.md'
  pull_request:
    branches:
      - staging
    paths:
      - 'application/backend/**'
      - '!application/backend/**/*.md'
      - '!**/*.md'

permissions:
  id-token: write
  contents: read

jobs:
  backend-staging:
    name: Backend Staging
    uses: ./.github/workflows/backend-reusable.yml
    with:
      environment: staging
      aws_region: 'eu-central-1'
      python_version: '3.11'
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN_STAGING }}
      deployment_bucket: ${{ secrets.DEPLOYMENT_BUCKET }}
      api_handler_lambda: ${{ secrets.api_handler_staging_lambda }}
      iot_processor_lambda: ${{ secrets.iot_processor_staging_lambda }}
