name: Backend Dev Environment

on:
  push:
    branches:
      - dev
    paths:
      - 'application/backend/**'
      - '.github/workflows/backend-dev.yml'
      - '.github/workflows/backend-reusable.yml'
      - '!application/backend/**/*.md'
  pull_request:
    branches:
      - dev
    paths:
      - 'application/backend/**'
      - '!application/backend/**/*.md'

permissions:
  id-token: write
  contents: read

jobs:
  backend-dev:
    name: Backend Dev
    uses: ./.github/workflows/backend-reusable.yml
    with:
      environment: dev
      aws_region: 'eu-central-1'
      python_version: '3.11'
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN_DEV }}
      deployment_bucket: ${{ secrets.DEPLOYMENT_BUCKET }}
      api_handler_lambda: ${{ secrets.api_handler_dev_lambda }}
      iot_processor_lambda: ${{ secrets.iot_processor_dev_lambda }}
